title: Cooper Simpson
email: simpson.r.cooper@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  All about Cooper Simpson, his projects, and his blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  RS-Coop

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Added post-initialization
name: Cooper Simpson
markdown: kramdown

defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
# - scope:
#     path: _pages
#     type: projects
#   values:
#     layout: project


collections_dir: collections

collections:
  research_projects:
    permalink: /:collection/:name
  class_projects:
    permalink: /:collection/:name
  personal_projects:
    permalink: /:collection/:name

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ".gitignore"
  - ".jekyll-cache"
  - CNAME
  - README.md

include: ['_pages']
