title: Cooper Simpson
email: simpson.r.cooper@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  All about myself (Cooper Simpson), my projects, and my blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  RS-Coop

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Added post-initialization
name: Cooper Simpson
markdown: kramdown

defaults:
- scope:
    path: ""
    type: "papers"
  values:
    layout: "paper"
- scope:
    path: ""
    type: "software"
  values:
    layout:
- scope:
    path: ""
    type: "posts"
  values:
    layout: "post"

collections_dir: collections

collections:
  papers:
    output: true
    permalink: /research/papers/:slug
  software:
    output: true
    permalink: /research/software/:slug

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ".gitignore"
  - ".jekyll-cache"
  - CNAME
  - README.md

# include: ['_pages']
